### ISSUE TITLE
【待定】BUG太多了，根本没法用

### ISSUE THREAD

**Issue by singer01** [zhiziqxd/program-site#1]

**Comment by zhiziqxd** [comment]
请您详细描述一下您遇到的问题，以便我们进行修改

**Comment by singer01** [comment]
> 请您详细描述一下您遇到的问题，以便我们进行修改

我输入“打倒邓小平走资派”后没有反应

**Comment by zhiziqxd** [comment]
请问您使用的是那个cpp程序呢

**Comment by singer01** [comment]
> 请问您使用的是那个cpp程序呢

任何一个都没有反应

**Comment by zhiziqxd** [comment]
您可能使用了错误的程序:如果您需要撰写文稿/编写程序，请使用code-plus.cpp,并且您在撰写违法内容的话，本人不进行负责

**Comment by singer01** [comment]
> 您可能使用了错误的程序:如果您需要撰写文稿/编写程序，请使用code-plus.cpp,并且您在撰写违法内容的话，本人不进行负责

没有违法啊，它提示我输入，我就输入了，然后程序就崩溃了

**Comment by zhiziqxd** [comment]
您使用的是那个程序呢

**Comment by singer01** [comment]
> 您使用的是哪个程序呢

code/test.cpp

**Comment by zhiziqxd** [comment]
遇到这种问题的话，请尝试更换操作系统/更换您使用的编译器

**Comment by zhiziqxd** [comment]
举个例子：比如您编写了计算器，然后请你在计算器内增加文件操作把输出换到指定的测试文件，并自己制作几个样例

**Comment by singer01** [comment]
> 举个例子：比如您编写了计算器，然后请你在计算器内增加文件操作把输出换到指定的测试文件，并自己制作几个样例

哦哦，我理解错了，抱歉

**Comment by zhiziqxd** [comment]
那么我们就结束问题了

**Comment by zhiziqxd** [comment]
注:违法内容本人不负责

**Comment by zhiziqxd** [comment]
我感觉我要被帽子叔叔找上门

**Comment by singer01** [comment]
> 我感觉我要被帽子叔叔找上门

？？？？怎么了
